spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: api-gateway
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

# 게이트웨이 담당, 모든 유저(혹은 프런트엔드)는 이 포트로 접속 -> 8080
server:
  port: 8080

# 유레카 서버의 서비스 정보 페이지 등록
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
  client:
    service-url:
      # 현재는 미구현 상태로 404임
      defaultZone: http://localhost:8761/eureka

front-ip: http://localhost:8081

jwt:
  token:
    secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}

logging:
  level:
    root: INFO
    com.example.apigateway.config.com.apigateway.config.JwtFilterConfig: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFilterFunction: DEBUG